---
openapi: 3.0.0
info:
  title: grade-prediction-api
  description: The API for Predicting Student Grades
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/17313/hw4/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /predict:
    get:
      tags:
      - Model
      description: uses ML model to predict if an applicant will be admitted based on certain attributes
      operationId: prediction
      responses:
        "200":
          description: Returns prediction of if student will  be admitted (0 for no, 1 for yes)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prediction'
  /applicants:
    get:
      tags:
      - Applicant
      description: gets attribute values for specific applicant to be evaluated by ML model; if no applicant given yet, default attribute values of 0 are returned
      operationId: getApplicant
      responses:
        "200":
          description: Values of applicant's attributes (or all 0 if no POST request made)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Applicants'
    post:
      tags:
      - Applicant
      description: add in an applicant to be evaluated by ML model
      operationId: postApplicant
      parameters:
      - name: applicant
        in: query
        description: applicant's values for attributes used in ML model
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/Applicants'
      responses:
        "200":
          description: Successfully input values for attributes used in ML model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Applicants'
        "400":
          description: Bad request due to client error. Not all attributes are found.
        "500":
          description: Bad request due to client error. Check the syntax of parameters and confirm that input is of type dictionary.
components:
  schemas:
    Prediction:
      type: object
      properties:
        admitted:
          type: integer
          format: admitted
          example: 0
    Applicants:
      type: object
      properties:
        attributes:
          type: integer
          properties:
            code:
              type: integer
            text:
              type: string
