---
openapi: 3.0.0
info:
  title: grade-prediction-api
  description: The API for Predicting Student Grades
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/17313/hw4/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /predict:
    get:
      tags:
      - Model
      description: uses ML model to predict scores and returns accuracy of predictions
      operationId: predictedScores
      responses:
        "200":
          description: Accuracy of scores predicted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prediction'
        "400":
          description: Bad request due to client errors. No attributes currently selected to predict applicant scores.
  /applicants:
    get:
      tags:
      - Applicant
      description: gets attributes used to train ML model
      operationId: getAttributes
      responses:
        "200":
          description: Selected attributes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Applicants'
        "400":
          description: Bad request due to client error. No attributes currently selected to predict applicant scores.
    post:
      tags:
      - Applicant
      description: change attributes used to train ML model
      operationId: selectAttributes
      parameters:
      - name: attributes
        in: query
        description: selected attributes to train ML model
        required: false
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/Applicants'
      responses:
        "200":
          description: Successfully selected attributes to train for ML model
          content:
            application/json:
              schema:
                type: string
                example: ok
        "400":
          description: Bad request due to client error. Check the syntax of parameters and http request.
components:
  schemas:
    Prediction:
      type: object
      properties:
        accuracyScore:
          type: number
          format: accuracyScore
          example: 0.5
    Applicants:
      type: object
      properties:
        attributes:
          type: array
          items:
            type: string
            format: attribute
            example: age
